[workspace]
authors = ["Brian Mc Donald <brian@brianmcdonald.me>"]
channels = ["conda-forge"]
name = "EET"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
uvicorn = ">=0.38.0,<0.39"

[pypi-dependencies]
fastapi = { version = ">=0.116.1, <0.117", extras = ["standard"] }
